spring.application.name=service-b
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/service_b
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092

topic.employee.created=employee.created
topic.employee.b.processed=employee.b.processed
topic.rollback.c=rollback.c
topic.rollback.b=rollback.b

topic.employee.rollback=employee.rollback


spring.kafka.consumer.auto-offset-reset=earliest


# Producer JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Important for JSON / POJO conversion
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Consumer group (each service should have unique)
spring.kafka.consumer.group-id=service-b

# --- Resilience4j Circuit Breaker ---
resilience4j.circuitbreaker.instances.serviceBProcessingCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.serviceBProcessingCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.serviceBProcessingCB.sliding-window-size=3
resilience4j.circuitbreaker.instances.serviceBProcessingCB.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.serviceBProcessingCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.serviceBProcessingCB.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.serviceBProcessingCB.permitted-number-of-calls-in-half-open-state=1
