version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
      args:
        SERVICE_NAME: service-a
    depends_on:
      - kafka
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/service_a
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
      args:
        SERVICE_NAME: service-b
    depends_on:
      - kafka
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/service_b
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  service-c:
    build:
      context: .
      dockerfile: service-c/Dockerfile
      args:
        SERVICE_NAME: service-c
    depends_on:
      - kafka
      - mysql
    ports:
      - "8082:8082"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/service_c
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root